package metadata

//Do not edit! This is an automatically generated file (see generator.GenerateExifTags()).
//This file was generated based on https://www.exiv2.org/tags.html

var GPSInfoValues = map[ExifTag]interface{}{}

var IFDValues = map[ExifTag]interface{}{
	IFD_SubfileType: map[uint16]string{
		0x1: "Full-resolution image",
		0x2: "Reduced-resolution image",
		0x3: "Single page of multi-page image",
	},
	IFD_Compression: map[uint16]string{
		0x1:    "Uncompressed",
		0x2:    "CCITT 1D",
		0x3:    "T4/Group 3 Fax",
		0x4:    "T6/Group 4 Fax",
		0x5:    "LZW",
		0x6:    "JPEG (old-style)",
		0x7:    "JPEG",
		0x8:    "Adobe Deflate",
		0x9:    "JBIG B&W",
		0xa:    "JBIG Color",
		0x63:   "JPEG",
		0x106:  "Kodak 262",
		0x7ffe: "Next",
		0x7fff: "Sony ARW Compressed",
		0x8001: "Packed RAW",
		0x8002: "Samsung SRW Compressed",
		0x8003: "CCIRLEW",
		0x8004: "Samsung SRW Compressed 2",
		0x8005: "PackBits",
		0x8029: "Thunderscan",
		0x8063: "Kodak KDC Compressed",
		0x807f: "IT8CTPAD",
		0x8080: "IT8LW",
		0x8081: "IT8MP",
		0x8082: "IT8BL",
		0x808c: "PixarFilm",
		0x808d: "PixarLog",
		0x80b2: "Deflate",
		0x80b3: "DCS",
		0x80eb: "Aperio JPEG 2000 YCbCr",
		0x80ed: "Aperio JPEG 2000 RGB",
		0x8765: "JBIG",
		0x8774: "SGILog",
		0x8775: "SGILog24",
		0x8798: "JPEG 2000",
		0x8799: "Nikon NEF Compressed",
		0x879b: "JBIG2 TIFF FX",
		0x879e: "Microsoft Document Imaging (MDI) Binary Level Codec",
		0x879f: "Microsoft Document Imaging (MDI) Progressive Transform Codec",
		0x87a0: "Microsoft Document Imaging (MDI) Vector",
		0x8847: "ESRI Lerc",
		0x884c: "Lossy JPEG",
		0x886d: "LZMA2",
		0x886e: "Zstd",
		0x886f: "WebP",
		0x8875: "PNG",
		0x8876: "JPEG XR",
		0xfde8: "Kodak DCR Compressed",
		0xffff: "Pentax PEF Compressed",
	},
	IFD_PhotometricInterpretation: map[uint16]string{
		0x0:    "WhiteIsZero",
		0x1:    "BlackIsZero",
		0x2:    "RGB",
		0x3:    "RGB Palette",
		0x4:    "Transparency Mask",
		0x5:    "CMYK",
		0x6:    "YCbCr",
		0x8:    "CIELab",
		0x9:    "ICCLab",
		0xa:    "ITULab",
		0x8023: "Color Filter Array",
		0x804c: "Pixar LogL",
		0x804d: "Pixar LogLuv",
		0x807c: "Sequential Color Filter",
		0x884c: "Linear Raw",
		0xc7e9: "Depth Map",
		0xcd2f: "Semantic Mask",
	},
	IFD_Thresholding: map[uint16]string{
		0x1: "No dithering or halftoning",
		0x2: "Ordered dither or halftone",
		0x3: "Randomized dither",
	},
	IFD_FillOrder: map[uint16]string{
		0x1: "Normal",
		0x2: "Reversed",
	},
	IFD_Orientation: map[uint16]string{
		0x1: "Horizontal (normal)",
		0x2: "Mirror horizontal",
		0x3: "Rotate 180",
		0x4: "Mirror vertical",
		0x5: "Mirror horizontal and rotate 270 CW",
		0x6: "Rotate 90 CW",
		0x7: "Mirror horizontal and rotate 90 CW",
		0x8: "Rotate 270 CW",
	},
	IFD_PlanarConfiguration: map[uint16]string{
		0x1: "Chunky",
		0x2: "Planar",
	},
	IFD_GrayResponseUnit: map[uint16]string{
		0x1: "0.1",
		0x2: "0.001",
		0x3: "0.0001",
		0x4: "1e-05",
		0x5: "1e-06",
	},
	IFD_ResolutionUnit: map[uint16]string{
		0x1: "None",
		0x2: "inches",
		0x3: "cm",
	},
	IFD_Predictor: map[uint16]string{
		0x1:    "None",
		0x2:    "Horizontal differencing",
		0x3:    "Floating point",
		0x884c: "Horizontal difference X2",
		0x884d: "Horizontal difference X4",
		0x884e: "Floating point X2",
		0x884f: "Floating point X4",
	},
	IFD_InkSet: map[uint16]string{
		0x1: "CMYK",
		0x2: "Not CMYK",
	},
	IFD_SampleFormat: map[uint16]string{
		0x1: "Unsigned",
		0x2: "Signed",
		0x3: "Float",
		0x4: "Undefined",
		0x5: "Complex int",
		0x6: "Complex float",
	},
	IFD_YCbCrPositioning: map[uint16]string{
		0x1: "Centered",
		0x2: "Co-sited",
	},
	IFD_CFALayout: map[uint16]string{
		0x1: "Rectangular",
		0x2: "Even columns offset down 1/2 row",
		0x3: "Even columns offset up 1/2 row",
		0x4: "Even rows offset right 1/2 column",
		0x5: "Even rows offset left 1/2 column",
		0x6: "Even rows offset up by 1/2 row, even columns offset left by 1/2 column",
		0x7: "Even rows offset up by 1/2 row, even columns offset right by 1/2 column",
		0x8: "Even rows offset down by 1/2 row, even columns offset left by 1/2 column",
		0x9: "Even rows offset down by 1/2 row, even columns offset right by 1/2 column",
	},
	IFD_MakerNoteSafety: map[uint16]string{
		0x0: "Unsafe",
		0x1: "Safe",
	},
	IFD_CalibrationIlluminant1: map[uint16]string{
		0x0:  "Unknown",
		0x1:  "Daylight",
		0x2:  "Fluorescent",
		0x3:  "Tungsten (Incandescent)",
		0x4:  "Flash",
		0x9:  "Fine Weather",
		0xa:  "Cloudy",
		0xb:  "Shade",
		0xc:  "Daylight Fluorescent",
		0xd:  "Day White Fluorescent",
		0xf:  "White Fluorescent",
		0x10: "Warm White Fluorescent",
		0x11: "Standard Light A",
		0x12: "Standard Light B",
		0x13: "Standard Light C",
		0x14: "D55",
		0x15: "D65",
		0xe:  "Cool White Fluorescent",
		0x16: "D75",
		0x17: "D50",
		0x18: "ISO Studio Tungsten",
		0xff: "Other",
	},
	IFD_CalibrationIlluminant2: map[uint16]string{
		0x0:  "Unknown",
		0x1:  "Daylight",
		0x2:  "Fluorescent",
		0x3:  "Tungsten (Incandescent)",
		0x4:  "Flash",
		0x9:  "Fine Weather",
		0xa:  "Cloudy",
		0xb:  "Shade",
		0xc:  "Daylight Fluorescent",
		0xd:  "Day White Fluorescent",
		0xf:  "White Fluorescent",
		0x10: "Warm White Fluorescent",
		0x11: "Standard Light A",
		0x12: "Standard Light B",
		0x13: "Standard Light C",
		0x14: "D55",
		0x15: "D65",
		0xe:  "Cool White Fluorescent",
		0x16: "D75",
		0x17: "D50",
		0x18: "ISO Studio Tungsten",
		0xff: "Other",
	},
	IFD_ProfileEmbedPolicy: map[uint32]string{
		0: "Allow Copying",
		1: "Embed if Used",
		2: "Never Embed",
		3: "No Restrictions",
	},
	IFD_PreviewColorSpace: map[uint32]string{
		0: "Unknown",
		1: "Gray Gamma 2.2",
		2: "sRGB",
		3: "Adobe RGB",
		4: "ProPhoto RGB",
	},
	IFD_ProfileHueSatMapEncoding: map[uint32]string{
		0: "Linear",
		1: "sRGB",
	},
	IFD_ProfileLookTableEncoding: map[uint32]string{
		0: "Linear",
		1: "sRGB",
	},
	IFD_DefaultBlackRender: map[uint32]string{
		0: "Auto",
		1: "None",
	},
	IFD_DepthFormat: map[uint16]string{
		0x0: "Unknown",
		0x1: "Linear",
		0x2: "Inverse",
	},
	IFD_DepthUnits: map[uint16]string{
		0x0: "Unknown",
		0x1: "Meters",
	},
	IFD_DepthMeasureType: map[uint16]string{
		0x0: "Unknown",
		0x1: "Optical Axis",
		0x2: "Optical Ray",
	},
	IFD_CalibrationIlluminant3: map[uint16]string{
		0x0:  "Unknown",
		0x1:  "Daylight",
		0x2:  "Fluorescent",
		0x3:  "Tungsten (Incandescent)",
		0x4:  "Flash",
		0x9:  "Fine Weather",
		0xa:  "Cloudy",
		0xb:  "Shade",
		0xc:  "Daylight Fluorescent",
		0xd:  "Day White Fluorescent",
		0xf:  "White Fluorescent",
		0x10: "Warm White Fluorescent",
		0x11: "Standard Light A",
		0x12: "Standard Light B",
		0x13: "Standard Light C",
		0x14: "D55",
		0x15: "D65",
		0xe:  "Cool White Fluorescent",
		0x16: "D75",
		0x17: "D50",
		0x18: "ISO Studio Tungsten",
		0xff: "Other",
	},
}

var ExifValues = map[ExifTag]interface{}{
	Exif_ExposureProgram: map[uint16]string{
		0x0: "Not Defined",
		0x1: "Manual",
		0x2: "Program AE",
		0x3: "Aperture-priority AE",
		0x4: "Shutter speed priority AE",
		0x5: "Creative (Slow speed)",
		0x6: "Action (High speed)",
		0x7: "Portrait",
		0x8: "Landscape",
		0x9: "Bulb",
	},
	Exif_SensitivityType: map[uint16]string{
		0x0: "Unknown",
		0x1: "Standard Output Sensitivity",
		0x2: "Recommended Exposure Index",
		0x3: "ISO Speed",
		0x4: "Standard Output Sensitivity and Recommended Exposure Index",
		0x5: "Standard Output Sensitivity and ISO Speed",
		0x6: "Recommended Exposure Index and ISO Speed",
		0x7: "Standard Output Sensitivity, Recommended Exposure Index and ISO Speed",
	},
	Exif_MeteringMode: map[uint16]string{
		0x0:  "Unknown",
		0x1:  "Average",
		0x2:  "Center-weighted average",
		0x3:  "Spot",
		0x4:  "Multi-spot",
		0x5:  "Multi-segment",
		0x6:  "Partial",
		0xff: "Other",
	},
	Exif_LightSource: map[uint16]string{
		0x0:  "Unknown",
		0x1:  "Daylight",
		0x2:  "Fluorescent",
		0x3:  "Tungsten (Incandescent)",
		0x4:  "Flash",
		0x9:  "Fine Weather",
		0xa:  "Cloudy",
		0xb:  "Shade",
		0xc:  "Daylight Fluorescent",
		0xd:  "Day White Fluorescent",
		0xf:  "White Fluorescent",
		0x10: "Warm White Fluorescent",
		0x11: "Standard Light A",
		0x12: "Standard Light B",
		0x13: "Standard Light C",
		0x14: "D55",
		0x15: "D65",
		0xe:  "Cool White Fluorescent",
		0x16: "D75",
		0x17: "D50",
		0x18: "ISO Studio Tungsten",
		0xff: "Other",
	},
	Exif_Flash: map[uint16]string{
		0x0:  "No Flash",
		0x1:  "Fired",
		0x5:  "Fired, Return not detected",
		0x7:  "Fired, Return detected",
		0x8:  "On, Did not fire",
		0x9:  "On, Fired",
		0xd:  "On, Return not detected",
		0xf:  "On, Return detected",
		0x10: "Off, Did not fire",
		0x14: "Off, Did not fire, Return not detected",
		0x18: "Auto, Did not fire",
		0x19: "Auto, Fired",
		0x1d: "Auto, Fired, Return not detected",
		0x1f: "Auto, Fired, Return detected",
		0x20: "No flash function",
		0x30: "Off, No flash function",
		0x41: "Fired, Red-eye reduction",
		0x45: "Fired, Red-eye reduction, Return not detected",
		0x47: "Fired, Red-eye reduction, Return detected",
		0x49: "On, Red-eye reduction",
		0x4d: "On, Red-eye reduction, Return not detected",
		0x4f: "On, Red-eye reduction, Return detected",
		0x50: "Off, Red-eye reduction",
		0x58: "Auto, Did not fire, Red-eye reduction",
		0x59: "Auto, Fired, Red-eye reduction",
		0x5d: "Auto, Fired, Red-eye reduction, Return not detected",
		0x5f: "Auto, Fired, Red-eye reduction, Return detected",
	},
	Exif_ColorSpace: map[uint16]string{
		0x1:    "sRGB",
		0x2:    "Adobe RGB",
		0xfffd: "Wide Gamut RGB",
		0xfffe: "ICC Profile",
		0xffff: "Uncalibrated",
	},
	Exif_FocalPlaneResolutionUnit: map[uint16]string{
		0x1: "None",
		0x2: "inches",
		0x3: "cm",
		0x4: "mm",
		0x5: "um",
	},
	Exif_SensingMethod: map[uint16]string{
		0x1: "Not defined",
		0x2: "One-chip color area",
		0x3: "Two-chip color area",
		0x4: "Three-chip color area",
		0x5: "Color sequential area",
		0x7: "Trilinear",
		0x8: "Color sequential linear",
	},
	Exif_CustomRendered: map[uint16]string{
		0x0: "Normal",
		0x1: "Custom",
		0x2: "HDR (no original saved)",
		0x3: "HDR (original saved)",
		0x4: "Original (for HDR)",
		0x6: "Panorama",
		0x7: "Portrait HDR",
		0x8: "Portrait",
	},
	Exif_ExposureMode: map[uint16]string{
		0x0: "Auto",
		0x1: "Manual",
		0x2: "Auto bracket",
	},
	Exif_WhiteBalance: map[uint16]string{
		0x0: "Auto",
		0x1: "Manua",
	},
	Exif_SceneCaptureType: map[uint16]string{
		0x0: "Standard",
		0x1: "Landscape",
		0x2: "Portrait",
		0x3: "Night",
		0x4: "Other",
	},
	Exif_GainControl: map[uint16]string{
		0x0: "None",
		0x1: "Low gain up",
		0x2: "High gain up",
		0x3: "Low gain down",
		0x4: "High gain down",
	},
	Exif_Contrast: map[uint16]string{
		0x0: "Normal",
		0x1: "Low",
		0x2: "High",
	},
	Exif_Saturation: map[uint16]string{
		0x0: "Normal",
		0x1: "Low",
		0x2: "High",
	},
	Exif_Sharpness: map[uint16]string{
		0x0: "Normal",
		0x1: "Soft",
		0x2: "Hard",
	},
	Exif_SubjectDistanceRange: map[uint16]string{
		0x0: "Unknown",
		0x1: "Macro",
		0x2: "Close",
		0x3: "Distant",
	},
	Exif_CompositeImage: map[uint16]string{
		0x0: "Unknown",
		0x1: "Not a Composite Image",
		0x2: "General Composite Image",
		0x3: "Composite Image Captured While Shooting",
	},
}

var IopValues = map[ExifTag]interface{}{
	Iop_InteroperabilityIndex: map[string]string{
		"R03": "R03 - DCF option file (Adobe RGB)",
		"R98": "R98 - DCF basic file (sRGB)",
		"THM": "THM - DCF thumbnail file",
	},
}
