version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errname
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - Id
            - []
          disabled: false
        - name: exported
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
