
run:
  timeout: 5m

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    #default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    #additional linters
    - errname
    - gocyclo
    - misspell
    - revive
    - gofmt

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: false
        arguments:
          - [ "ID", "Id" ] # AllowList
          - [] # DenyList
      - name: exported
        disabled: false
        severity: warning

