name: Test

on:
  push:
  pull_request:

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26'

      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --verbose

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26'

      - run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  golangci-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - macOS-latest
        go:
        - '1.25'
        - '1.26'
    name: '${{ matrix.platform }} | ${{ matrix.go }}'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
